name = "Logfire"
uuid = "afd33542-d123-4ba1-bea0-67b5a7deb1ad"
authors = ["J S @svilupp and contributors"]
version = "0.1.0"

[deps]
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OpenAI = "e9f21f70-7185-4079-aca2-91159181367c"
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
OpenTelemetryExporterOtlpProtoHttp = "f175482f-0544-4037-b362-361efbf21c04"
OpenTelemetrySDK = "f5929ecf-be04-446c-b2f2-494e1fe70ee4"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[extensions]
LogfirePromptingToolsExt = "PromptingTools"

[compat]
DotEnv = "1.0"
HTTP = "1.10.19"
JSON3 = "1.14.3"
OpenAI = "0.11.0"
OpenTelemetryAPI = "0.5.2"
OpenTelemetryExporterOtlpProtoHttp = "0.1.5"
OpenTelemetrySDK = "0.4.2"
PromptingTools = "0.88"
StructTypes = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JSON3", "PromptingTools", "Test"]
